# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieinfo',
            options={'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='myimg',
            field=models.ImageField(default='', upload_to='myimg/', verbose_name='我的图片'),
            preserve_default=False,
        ),
    ]
