# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20171026_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='myimg',
            field=models.ImageField(blank=True, upload_to='myimg/', verbose_name='我的图片'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mymovies',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movies.MovieInfo', verbose_name='我的收藏'),
        ),
    ]
