# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20171026_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mymovies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.MovieInfo', verbose_name='我的收藏'),
        ),
    ]
