# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20171026_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='mymovies',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mymovies',
            field=models.ManyToManyField(null=True, to='movies.MovieInfo', verbose_name='我的收藏'),
        ),
    ]
